export interface Device {
  MacAddressId: string;
}

export interface RemoteState {
  SystemOn: number;
  MacAddressId: string;
  DateKey: number;
  TimeKey: number;
  TimeRunning: string;
  CoolerType: number;
  TouchCount: number;
  ExternalTemp: number;
  InternalTemp: number;
  EvapCRunning: number;
  FanOrTempControl: number;
  PumpStatus: number;
  CFanOnlyOrCool: number;
  NightQuietMode: number;
  PumpOffExternalAirSensor: number;
  DrainExternalSensor: number;
  ManualDrain: number;
  PadFlush: number;
  AutoClean: number;
  DrainDry: number;
  FaultCodePresent: number;
  CFanSpeed: number;
  CTemp: number;
  HumiditySetPoint: number;
  HumidityActualValue: number;
  Fault: number;
  HRunning: number;
  HFanOnly: number;
  BasicFault: number;
  Spanner: number;
  HFanSpeed: number;
  HActualFanSpeed: number;
  HActualGasRate: number;
  HSetGasRate: number;
  HTemp: number;
  HActualGasRateVariable: number;
  ThermistorTemperature: number;
  HNewFault: number;
  FlameSenseVoltage: number;
  FAOCRunning: number;
  FAOCActualCompressorON: number;
  FAOCTemp: number;
  IAOCRunning: number;
  IAOCCompressorON: number;
  IAOCSetTemp: number;
  IAOCActualTemp: number;
  ProgramMode: number;
  ProgramModeOverridden: number;
  UpdateMicroProcessor: number;
  UpdateWiFiModule: number;
  ClearSoftwareUpdate: number;
  LoggingFrequency: number;
  EnableLiveStreaming: number;
  UpdateInPogress: number;
  UpdateCompleted: number;
  UpdateFailed: number;
  SignalStrength: number;
  OnOffZone1: number;
  DamperOnOffZone1: number;
  ProgramModeZone1: number;
  ProgramModeOverriddenZone1: number;
  SetTempZone1: number;
  ActualTempZone1: number;
  OnOffZone2: number;
  DamperOnOffZone2: number;
  ProgramModeZone2: number;
  ProgramModeOverriddenZone2: number;
  SetTempZone2: number;
  ActualTempZone2: number;
  OnOffZone3: number;
  DamperOnOffZone3: number;
  ProgramModeZone3: number;
  ProgramModeOverriddenZone3: number;
  SetTempZone3: number;
  ActualTempZone3: number;
  OnOffZone4: number;
  DamperOnOffZone4: number;
  ProgramModeZone4: number;
  ProgramModeOverriddenZone4: number;
  SetTempZone4: number;
  ActualTempZone4: number;
  OnOffZone5: number;
  DamperOnOffZone5: number;
  ProgramModeZone5: number;
  ProgramModeOverriddenZone5: number;
  SetTempZone5: number;
  ActualTempZone5: number;
  OnOffZone6: number;
  DamperOnOffZone6: number;
  ProgramModeZone6: number;
  ProgramModeOverriddenZone6: number;
  SetTempZone6: number;
  ActualTempZone6: number;
  OnOffZone7: number;
  DamperOnOffZone7: number;
  ProgramModeZone7: number;
  ProgramModeOverriddenZone7: number;
  SetTempZone7: number;
  ActualTempZone7: number;
  OnOffZone8: number;
  DamperOnOffZone8: number;
  ProgramModeZone8: number;
  ProgramModeOverriddenZone8: number;
  SetTempZone8: number;
  ActualTempZone8: number;
  OnOffZone9: number;
  DamperOnOffZone9: number;
  ProgramModeZone9: number;
  ProgramModeOverriddenZone9: number;
  SetTempZone9: number;
  ActualTempZone9: number;
  OnOffZone10: number;
  DamperOnOffZone10: number;
  ProgramModeZone10: number;
  ProgramModeOverriddenZone10: number;
  SetTempZone10: number;
  ActualTempZone10: number;
}

export interface RemoteAccessRequest {
  SerialNo: string;
  TimeRequest: string;
  StandBy: number;
  EvapCRunning: number;
  CTemp: number;
  CFanSpeed: number;
  CFanOnly: number;
  CThermosOrFan: number;
  HRunning: number;
  HTemp: number;
  HFanSpeed: number;
  HFanOnly: number;
  FAOCRunning: number;
  FAOCTemp: number;
  IAOCRunning: number;
  IAOCTemp: number;
  OnOffZone1: number;
  TempZone1: number;
  Override1: number;
  OnOffZone2: number;
  TempZone2: number;
  Override2: number;
  OnOffZone3: number;
  TempZone3: number;
  Override3: number;
  OnOffZone4: number;
  TempZone4: number;
  Override4: number;
  OnOffZone5: number;
  TempZone5: number;
  Override5: number;
  OnOffZone6: number;
  TempZone6: number;
  Override6: number;
  OnOffZone7: number;
  TempZone7: number;
  Override7: number;
  OnOffZone8: number;
  TempZone8: number;
  Override8: number;
  OnOffZone9: number;
  TempZone9: number;
  Override9: number;
  OnOffZone10: number;
  TempZone10: number;
  Override10: number;
  CC3200FW_Major: number;
  CC3200FW_Minor: number;
  STM32FW_Major: number;
  STM32FW_Minor: number;
  TouchCount: number;
}

interface SystemDeviceCommon {
  MinimumTemperature: number;
  MaximumTemperature: number;
}

export interface SystemDetails {
  NoOfZones: number;
  NoOfZonesControl: number;
  HeaterInSystem: number;
  AOCInverterInSystem: number;
  AOCFixedInSystem: number;
  NoOfEVAPInSystem: number;
  Heater: SystemDeviceCommon & { AOCInstalled: number };
  AOCFixed: SystemDeviceCommon;
  AOCInverter: SystemDeviceCommon;
  EVAPCooler: SystemDeviceCommon;
  ZoneName1: string;
  ZoneName2: string;
  ZoneName3: string;
  ZoneName4: string;
  ZoneName5: string;
  ZoneName6: string;
  ZoneName7: string;
  ZoneName8: string;
  ZoneName9: string;
  ZoneName10: string;
}

export function newStateRequest(state: RemoteState): RemoteAccessRequest {
  return {
    SerialNo: state.MacAddressId,
    TimeRequest: new Date().toISOString(),
    StandBy: state.SystemOn ? 0 : 1,
    EvapCRunning: state.EvapCRunning,
    CTemp: state.CTemp,
    CFanSpeed: state.CFanSpeed,
    CFanOnly: state.CFanOnlyOrCool,
    CThermosOrFan: state.CFanOnlyOrCool ? 0 : state.FanOrTempControl,
    HRunning: state.HRunning,
    HTemp: state.HTemp,
    HFanSpeed: state.HFanSpeed,
    HFanOnly: state.HFanOnly,
    FAOCRunning: state.FAOCRunning,
    FAOCTemp: state.FAOCTemp,
    IAOCRunning: state.IAOCRunning,
    IAOCTemp: state.IAOCSetTemp,
    OnOffZone1: state.OnOffZone1,
    TempZone1: state.SetTempZone1,
    Override1: state.ProgramModeOverriddenZone1,
    OnOffZone2: state.OnOffZone2,
    TempZone2: state.SetTempZone2,
    Override2: state.ProgramModeOverriddenZone2,
    OnOffZone3: state.OnOffZone3,
    TempZone3: state.SetTempZone3,
    Override3: state.ProgramModeOverriddenZone3,
    OnOffZone4: state.OnOffZone4,
    TempZone4: state.SetTempZone4,
    Override4: state.ProgramModeOverriddenZone4,
    OnOffZone5: state.OnOffZone5,
    TempZone5: state.SetTempZone5,
    Override5: state.ProgramModeOverriddenZone5,
    OnOffZone6: state.OnOffZone6,
    TempZone6: state.SetTempZone6,
    Override6: state.ProgramModeOverriddenZone6,
    OnOffZone7: state.OnOffZone7,
    TempZone7: state.SetTempZone7,
    Override7: state.ProgramModeOverriddenZone7,
    OnOffZone8: state.OnOffZone8,
    TempZone8: state.SetTempZone8,
    Override8: state.ProgramModeOverriddenZone8,
    OnOffZone9: state.OnOffZone9,
    TempZone9: state.SetTempZone9,
    Override9: state.ProgramModeOverriddenZone9,
    OnOffZone10: state.OnOffZone10,
    TempZone10: state.SetTempZone10,
    Override10: state.ProgramModeOverriddenZone10,
    CC3200FW_Major: 0,
    CC3200FW_Minor: 0,
    STM32FW_Major: 0,
    STM32FW_Minor: 0,
    TouchCount: 0,
  };
}
